### ISSUE TITLE
Joomla! Anti-Malware Scan Script - JED checker

### ISSUE THREAD

**Issue by zikkuratvk** [AlekVolsk/cfi#1]
#001 /cfi.php in line: 139
info code Pattern found#17 - PHP: multiple encoded, most probably obfuscated code found
#002 /cfi.php in line: 262
info code Pattern found#21 - At least two characters in hexadecimal or octal notation
#003 /cfi.php in line: 28
info code Pattern found#24 - PHP execution operator: backticks (``)
#004 /script.php in line: 18
info code Pattern found#24 - PHP execution operator: backticks (``)

![image](https://user-images.githubusercontent.com/2261206/70866704-90407700-1f75-11ea-8485-7edecb16823b.png)

**Comment by AlekVolsk** [comment]
1) ложное срабатывание
2) - 4) фикс в 1.0.3
