### ISSUE TITLE
Feedback #1 - update https://joomline.org/extensions/scripts-other-developments/cfi.html

### ISSUE THREAD

**Issue by woluweb** [AlekVolsk/cfi#10]
Hi @AlekVolsk 

*Thank you very very much* for this excellent plugin!
I had already tested it very quicky when I had written https://magazine.joomla.org/all-issues/august-2021/custom-fields-episode-6-make-more-with-extensions (as you might know, I am a big fan and evangelist of Joomla Custom Fields :) )

Now I have a very good usecase for CFI and so I am testing it more in details.

I have several feedbacks so I will create a separate "Issue" for each of them, so that it is easier for you to manage.

Here is the Feedback #1 : on https://joomline.org/extensions/scripts-other-developments/cfi.html 
1. it is not said that the plugin is J4 compatible (it only mentions J3)
2. and also the version number is 1.0.4 and not the current version 1.0.11

**Comment by woluweb** [comment]
PS: one additional comment: in the Documentation but also on the JED and even in the Description of this Repo, the word "additional fields" is used... while Joomla calls it "Custom Fields". Many Joomlers might miss this very nice plugin just because they don't realize that you mean "Custom Fields" when saying "additional fields" ;)

**Comment by AlekVolsk** [comment]
Translation is a trifle, we'll fix it. I am not responsible for the publication on JoomLine and other resources, I cannot help here.
