### ISSUE TITLE
Feedback #2 - characters with accents (éèàç etc) are exported as "?"

### ISSUE THREAD

**Issue by woluweb** [AlekVolsk/cfi#11]
My website is in French, which uses characters with accents, like é è à ç etc.

When I export with CFI, those accents are exported/replaced with a `?` sign (no matter if I open with Excel or with Notepad++, even if I change the encoding in Notepad++).

I saw that the CFI plugin has an Option to change the encoding.
But when reading the Documentation, if I understand properly (the translation to English is sometimes a bit difficult to understand), that Option is only for Import (not for Export) anyway.

Could this be fixed?
(Or should I play with that Encoding Option?)

**Comment by AlekVolsk** [comment]
Encoding should work both ways. Unfortunately, the encoding is highly dependent on the locales installed on the server, and it may not work correctly if the locale of your language is not installed on the server where your site is located. Special encoders are not used and are not planned.

If you develop an additional custom encoding solution for a specific encoding and your solution can be considered universal, I will try to implement support for such a solution.

**Comment by woluweb** [comment]
Txs for all you answers @AlekVolsk 
But for accents, I am a bit puzzled: maybe I misunderstood what the checkbox "convert encoding" does, but
- of course I have different csv file for each format chosen in the plugin
- but that csv file is always exactlly the same whether
  - I check the checkbox to convert encoding
  - I disable the checkbox to NOT convert encoding
Is the checkbox working then?
Txs

**Comment by AlekVolsk** [comment]
i can't check for french, for russian (cp-1251) everything works fine

**Comment by woluweb** [comment]
well, if you could simply check for French by typing the Title of this Issue, you have accented characters ;)
Bc if it works for you, then the issue is elsewhere and I can investigate further  (collation of table ? configuration of server ?)
