### ISSUE TITLE
Feedback #3 - when exporting, all Custom Fields are mentioned... even when not assigned to the chosen Category

### ISSUE THREAD

**Issue by woluweb** [AlekVolsk/cfi#12]
As you know, in Joomla you can assign each Custom Field to given Category.

But when exporting, CFI creates a column for absolutely all Custom Fields, even if they are not assigned to the Category.
I guess it would be better to create a check so that it only exports the assigned Custom Fields.
So this is a little feature request :)

Besides, a little related question: if I import a file, I guess that I don't need to have a column for each of those unnecessary Custom Fields?
I mean: I guess that if I don't have a column for a given Custom Field when importing, that Custom Field is simply ignored anyway?

**Comment by AlekVolsk** [comment]
This is a good suggestion, I will think about its implementation, but for now, unfortunately, in the coming months, I do not have time for this.

**Comment by woluweb** [comment]
This is just a "Nice To Have" so no urgency of course
Just tell me if you want me to test new future versions (whatever the new fixes/features/...).

**Comment by AlekVolsk** [comment]
It's always nice to have an independent tester, but it's always a charity: if you want - I can't forbid you)
