### ISSUE TITLE
Feedback #4 - Intro Image and Full Image are missing

### ISSUE THREAD

**Issue by woluweb** [AlekVolsk/cfi#13]
When exporting (or importing I guess) there is no column for Intro Image and Full Image.
This would be useful though, because otherwise one has to manually edit 1000 articles after importing 1000 articles.

Of course, I am aware that the user who will use a "introimage" and "fullimage" column will have to manually upload it via FTP (independently of CFI of course), but this is what your Documentation already mentions.

So this is a little Feature Request if I may: adding the possibility for Intro Image and Full Image :)

**Comment by AlekVolsk** [comment]
This is a controversial suggestion: this solution is intended for custom fields only, the introduction of support for individual main fields will entail the desire to implement all fields of the material in general, which will greatly complicate the development and maintenance of the plugin as a whole.

I was repeatedly asked for such support, trying to make this plugin a solution for migrating materials from one site to another, but I contradict the original concept of the plugin and I will not make a universal master key for every day.
