### ISSUE TITLE
Feedback #5 - little styling issue with the buttons in J4

### ISSUE THREAD

**Issue by woluweb** [AlekVolsk/cfi#14]
I have not tested in J3 but in J4 there are a few styling issues in the backend. Examples:
1. the icon on the "Import and export CSV" button is only visible when hovering
2. the "Export articles" button does not have the button style
3. (the dropdown with the list of categories is not vertically aligned)

**Comment by AlekVolsk** [comment]
Fair remark. When adapting to J4, I did not correct the appearance, focusing on functionality. At the moment, my strong employment does not allow me to focus on this, but I will fix everything, closer to winter, sorry for the delays
