### ISSUE TITLE
Joomla Framework deprecated and unsafe  - JED checker

### ISSUE THREAD

**Issue by zikkuratvk** [AlekVolsk/cfi#2]
#001 /cfi.php in line: 157
Use of superglobals is strongly discouraged:
'file' => $_FILES,

#002 /cfi.php in line: 158
Use of superglobals is strongly discouraged:
'get' => $_GET,

#003 /cfi.php in line: 159
Use of superglobals is strongly discouraged:
'post' => $_POST

![image](https://user-images.githubusercontent.com/2261206/70866719-cd0c6e00-1f75-11ea-9a3d-f3f370c4e3f8.png)

**Comment by AlekVolsk** [comment]
фикс в 1.0.3
