### ISSUE TITLE
Base64 or other type of encoding in the files - JED checker

### ISSUE THREAD

**Issue by zikkuratvk** [AlekVolsk/cfi#3]
#001: /cfi.php
You've used encoding in this file. This is not an error, but a JED editor will have to review this file.

![image](https://user-images.githubusercontent.com/2261206/70866730-f1684a80-1f75-11ea-890e-ef4ffed6d330.png)

Официальный взгляд: 

As developers we are fully aware that the base64 and similar functions have a valid place in extensions (such as URL redirects or data storage). However if you use those to make it harder for users to read your code or to mask backlinks the JED will not accept your listing submission (this is not in the spirit of GPL anyway!). An editor will review your code and determine if the way you use the base64 matches the rules of the JED. This might slow your listing review time. So the rule of thumb is - don't do fishy stuff and avoid encoding your code if possible!

**Comment by AlekVolsk** [comment]
фикс в 1.0.3
