### ISSUE TITLE
[1.0.8] Button in articles view do nothing

### ISSUE THREAD

**Issue by SemaphoreOxalis** [AlekVolsk/cfi#5]
Fresh install on J! 3.9.25.  When we look at the DOM we can't see any event/js assign to the export/import button.

Thanks

**Comment by AlekVolsk** [comment]
The button should not be shown in the article view mode, only in the list mode, in which it works great.

**Comment by SemaphoreOxalis** [comment]
Indeed, I'm talking about the articleS so the list mode. I'll will retry with another fresh install but this one is not working.

**Comment by AlekVolsk** [comment]
Fixed in v1.0.9

**Comment by SemaphoreOxalis** [comment]
Hi,
Indeed the button "do something" now but the  export csv (converter not checked) is not readable by a software like Libreoffice but works fine with firefox because I think there is something wrong with the fileheader/MIME. The csv is recognized as a html file.
Thanks

**Comment by AlekVolsk** [comment]
This is another problem, the original problem is solved.

Most likely you do not specify the encoding you need for a file or did not turn off the encoding if you need the UTF-8 file. Read the docs.
