### ISSUE TITLE
Формат импорта пользовательских полей для прайса.

### ISSUE THREAD

**Issue by bombapiter** [AlekVolsk/cfi#7]
Здравствуйте.

Плагин полезный, пробую его использовать.

Вопрос:

При импорте пользовательских полей какой формат записи использовать?

Тот которые мы получаем при экспорте, как в базе записано?

`

{"price-name-description0":{"Sub-category":"\u0423\u0445\u043e\u0434 \u0437\u0430 \u0442\u0435\u043b\u043e\u043c","Name":"SMAS \u043b\u0438\u0444\u0442\u0438\u043d\u0433 \u043b\u0438\u0446\u0430 800 \u043b\u0438\u043d\u0438\u0439","Price":"52000","Description":"\u0422\u0443\u0440\u0435\u0446\u043a\u0438\u0439 \u043f\u0435\u043d\u043d\u044b\u0439 \u043c\u0430\u0441\u0441\u0430\u0436 60 \u043c\u0438\u043d.\r\n"},"price-name-description1":{"Sub-category":"\u0423\u0445\u043e\u0434 \u0437\u0430 \u0442\u0435\u043b\u043e\u043c","Name":"SMAS \u043b\u0438\u0444\u0442\u0438\u043d\u0433 \u043b\u0438\u0446\u0430 500 \u043b\u0438\u043d\u0438\u0439","Price":"32500","Description":"fss sfd sfd sdf"},"price-name-description2":{"Sub-category":"\u0423\u0445\u043e\u0434 \u0437\u0430 \u0442\u0435\u043b\u043e\u043c","Name":"SMAS \u043b\u0438\u0444\u0442\u0438\u043d\u0433 \u043b\u0438\u0446\u0430 300 \u043b\u0438\u043d\u0438\u0439","Price":"19500","Description":"\u0432\u043f\u0430 \u0432\u0430 \u043f\u0432\u0430\u044b\u043f"},"price-name-description3":{"Sub-category":"\u0423\u0445\u043e\u0434 \u0437\u0430 \u0442\u0435\u043b\u043e\u043c","Name":"SMAS \u043b\u0438\u0444\u0442\u0438\u043d\u0433 \u043b\u0438\u0446\u0430 \u0438 \u0448\u0435\u0438 1000 \u043b\u0438\u043d\u0438\u0439","Price":"65000","Description":"\u043f \u0432\u0430\u043f \u0432\u0430\u043f \u0430\u0432\u043f \u0430\u0432"}}
`

Но это же не реально? Теряется весь смысл плагина!

**Comment by AlekVolsk** [comment]
Формат - CSV, никакой другой MS Excel не откроет. У вас приведён как пример JSON - этот формат был бы слишком прост для реализации, но MS Excel, ради поддержки которого всё задумывалось, его не понимает.
