### ISSUE TITLE
Version for Joomla 4 ?

### ISSUE THREAD

**Issue by woluweb** [AlekVolsk/cfi#9]
Hi Alek,

It is only today that I discover your CFI extension.
It is really great, especially that it imports/exports Custom Fields and not only the Article Title/Text!

Do you have any plans to adapt it to Joomla 4 ?
(because it would be a nice way to migrate from J3 to J4 starting from a clean J4 installation)

Txs

**Comment by AlekVolsk** [comment]
Adaptation under J4 is planned during the next summer. Thank you for your interest in this solution.

**Comment by woluweb** [comment]
That's excellent news :)
Txs a lot (y)

**Comment by damarkuzz** [comment]
Need it too please!!

**Comment by AlekVolsk** [comment]
Adapted to Joomla 4 in v1.0.11
